apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  index.html:
    |-
      <html>
        <head>
          <title>Welcome to nginx!</title>
        </head>
        <body>
          <h1>Hello from the other sideee!</h1>
        </body>
      </html>